package com.exponea.sdk.models

enum class Routes {
    TRACK_CUSTOMERS,
    TRACK_EVENTS,
    TOKEN_ROTATE,
    TOKEN_REVOKE,
    CUSTOMERS_PROPERTY,
    CUSTOMERS_ID,
    CUSTOMERS_SEGMENTATION,
    CUSTOMERS_EXPRESSION,
    CUSTOMERS_PREDICTION,
    CUSTOMERS_RECOMMENDATION,
    CUSTOMERS_ATTRIBUTES,
    CUSTOMERS_EVENTS,
    CUSTOMERS_ANONYMIZE,
    CUSTOMERS_EXPORT_ALL_PROPERTIES,
    CIUSTOMERS_EXPORT_ALL
}